- hosts: tomcatgroup
  remote_user: root
  tasks:
#install java
     - name: copy and unarchive java
       unarchive: src=/tools/jdk-8u161-linux-x64.tar.gz dest=/opt/
     - name: rename
       command: mv /opt/jdk1.8.0_161 /opt/java
     - name: add /etc/profile
       lineinfile: dest=/etc/profile regexp="^JAVA_HOME=" line="JAVA_HOME=/opt/java/"
     - name: add /etc/profile
       lineinfile: dest=/etc/profile regexp="^CLASS_PATH=" line="CLASS_PATH=$JAVA_HOME/lib:$JAVA_HOME/jre/lib"
     - name: add /etc/profile
       lineinfile: dest=/etc/profile regexp="^PATH=\$PATH:\$JAVA_HOME" line="PATH=$PATH:$JAVA_HOME/bin"
     - name: add /etc/profile
       lineinfile : dest=/etc/profile regexp="^export JAVA_HOME" line="export JAVA_HOME"
     - name: source
       shell: '. /etc/profile'
#install tomcat
     - name: group
       group: name=tomcat
     - name: user
       user: name=user group=tomcat home=/usr/tomcat
     - name: copy tomcat
       unarchive: src=/tools/apache-tomcat-9.0.4.tar.gz dest=/opt/
     - name: link tomcat
       shell: 'mv /opt/apache-tomcat-9.0.4 /opt/tomcat'
     - name: owner
       file: path=/opt/tomcat owner=tomcat group=tomcat state=directory recurse=yes
     - name: copy jsvc
       copy: src=/tools/jsvc dest=/opt/tomcat/bin/jsvc mode=0755
     - name: copy tomcatservice
       copy: src=/tools/tomcat.service dest=/usr/lib/systemd/system/tomcat.service mode=0755
     - name: copy setclasspath
       copy: src=/tools/apache-tomcat-9.0.4/bin/setclasspath.sh dest=/opt/tomcat/bin/setclasspath.sh mode=0755 force=yes
     - name: start tomcat
       service: name=tomcat state=started enabled=yes
